### ISSUE TITLE
Chat access

### ISSUE THREAD

**Issue by sjors1955** [lfdversluis/mst#1073]
I was trying to use the app to stream a tour of ny it worked fine more or less it was a bit choppy. The issue I had though was the lack of acess to my chat. I tried to pull up the twitch app but then I couldn't watch what I was recording. I think it would be super useful to have chat acess along wwith the video so I don't have to switch apps or have 2 devices. Espeically for on the go streaming. Thanks. AllonsyOswin

**Comment by lfdversluis** [comment]
Is suggested, will be done eventually :)
