### ISSUE TITLE
Change stream key / authorized ads

### ISSUE THREAD

**Issue by sjors1955** [lfdversluis/mst#178]
Hi, to authenticate Twitch, you ask for permission to change my stream key and authorize ads. Why do you need to change the stream key? If you authorize ads, do you capitalize on people's streams?

**Comment by lfdversluis** [comment]
Change key is a permission that comes when requesting streaming rights from the API. We do not change any steam key though. Ads are in there to give us some revenue in return for our hard work. They can be turned off in the settings panel.
