### ISSUE TITLE
I like it 

### ISSUE THREAD

**Issue by sjors1955** [lfdversluis/mst#19]
I like the app but can you make it so you can play games that are on your iPod or tablet or phone like can you please make it so I can play the games I have on my iPod

**Comment by lfdversluis** [comment]
Sounds like screen streaming. On iOS...?

**Comment by devos50** [comment]
Not possible unfortunately, maybe at some point in the future we can create a framework that developers can integrate and allows this functionality (I believe Twitch has released one a long time but they removed it).
