### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by sjors1955** [lfdversluis/mst#357]
The Google play page for your app is misleading. This does not even have the ability to stream your screen to twitch. Perhaps you do not know what twitch is for. Also, it would appear that you will not be able to stream your screen AND your camera at the same time. This is much less useful than other existing streaming apps.

**Comment by lfdversluis** [comment]
If you read carefully you would've seen it is still in alpha, meaning functionality is broken -- and screen streaming is currently. Camera + screen will be worked on, but will take some time.
